[project]
name = "data-loader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "taskiq>=0.11.20",
    "taskiq-redis>=1.1.2",
]
