version: '3.10'
name: vtb_banking

services:
  postgres:
    image: postgres:18.0-alpine
    container_name: vtb_banking.postgres
    hostname: vtb_banking.postgres
    profiles: ["backend"]
    volumes:
      - vtb_banking.postgres.data:/var/lib/postgresql/data
    env_file:
      - ./backend/postgres/.env
    networks:
      - vtb_banking.postgres.network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.2-alpine
    container_name: vtb_banking.redis
    hostname: vtb_banking.redis
    profiles: ["backend"]
#    ports:
#      - "6379:6379"
    networks:
      - vtb_banking.redis.network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  user_api:
    container_name: vtb_banking.user_api
    hostname: vtb_banking.user_api
    profiles: ["backend"]
    build:
      context: ./backend/user_api
    ports:
      - "8000:8000"
    volumes:
      #- ./user_api/entrypoint.sh:/src/entrypoint.sh
#      - ./web/logger_file.ndjson:/src/logs/logger_file.ndjson
      - ./backend/user_api/openapi:/src/openapi
      - ./backend/user_api/src:/src
    env_file:
      - ./backend/user_api/.env
      - ./backend/postgres/.env
    networks:
      - vtb_banking.user_api.network
      - vtb_banking.redis.network
      - vtb_banking.postgres.network
      - vtb_banking.kafka.network
      - vtb_banking.clickhouse.network
    depends_on:
      - postgres
      - redis
      - kafka
      - clickhouse

  data_loader: &worker
    container_name: vtb_banking.data_loader
    hostname: vtb_banking.data_loader
    profiles: ["data_loader"]
    build:
      context: ./backend/data_loader
    volumes:
      - ./backend/data_loader/src:/src
    env_file:
      - ./backend/data_loader/.env
      - ./backend/postgres/.env
    networks:
      - vtb_banking.data_loader.network
      - vtb_banking.postgres.network
      - vtb_banking.kafka.network
      - vtb_banking.clickhouse.network
    depends_on:
      - postgres
      - kafka
      - clickhouse

  kafka:
    container_name: vtb_banking.kafka
    hostname: vtb_banking.kafka
    profiles: [ "data_loader" ]
    image: apache/kafka:latest
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_LOG4J_LOGGERS: "kafka=ERROR,kafka.controller=ERROR,kafka.server=ERROR"
    volumes:
      - vtb_banking.kafka.data:/var/lib/kafka/data
    networks:
      - vtb_banking.kafka.network
      - vtb_banking.clickhouse.network

  clickhouse:
    container_name: vtb_banking.clickhouse
    hostname: vtb_banking.clickhouse
    profiles: ["data_loader"]
    image: clickhouse/clickhouse-server:25.7-alpine
    env_file: ./backend/data_loader/.env
    volumes:
      - vtb_banking.clickhouse.data:/var/lib/clickhouse
      - ./backend/clickhouse:/docker-entrypoint-initdb.d
    networks:
      - vtb_banking.clickhouse.network
      - vtb_banking.kafka.network
    depends_on:
      - kafka

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: vtb_banking.frontend
    hostname: vtb_banking.frontend
    profiles: ["frontend"]
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      # Apps vars
      - NODE_ENV=production
      - VITE_HOST=0.0.0.0
      - VITE_PORT=80
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/dist:/app/dist:ro
    networks:
      - vtb_banking.frontend.network

volumes:
  vtb_banking.postgres.data: {}
  vtb_banking.clickhouse.data: {}
  vtb_banking.kafka.data: {}

networks:
  vtb_banking.user_api.network: {}
  vtb_banking.postgres.network: {}
  vtb_banking.redis.network: {}
  vtb_banking.kafka.network: {}
  vtb_banking.clickhouse.network: {}
  vtb_banking.frontend.network: {}
  vtb_banking.data_loader.network: {}
